name: vulns
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  vulns:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: install depm
        run: |
          pushd $RUNNER_TEMP
          curl -Lfs -o depm.tar.gz https://github.com/goark/depm/releases/download/v0.4.5/depm_0.4.5_Linux_64bit.tar.gz
          sudo tar -xzf depm.tar.gz
          sudo mv depm /usr/local/bin/depm
          popd
      - name: WriteGoList
        run: depm list --json > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
